apiVersion: v1
kind: ReplicationController
metadata:
  name : myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
   template:
      metadata:
         name: myapp-pod
         labels:
           app: mypp
           type: front-end
      spec:
         containers:
         - name: java-docker-tomcat
           image: mlk227/java-docker-tomcat
replicas: 3
